import type { Metadata } from "next";
import {Ubuntu} from "next/font/google";
import "./globals.css";

import { ToastLib } from "./providers/ToastLib";
import { getCurrentUser } from "./action/getCurrentUser";
import { getAllYears} from "./action/handleYears";
import { RegisterModal } from "./component/modal/RegisterModal";
import { LoginModal } from "./component/modal/LoginModal";
import { Header } from "./component/Header";
import { ClientOnly } from "./component/genetic/ClientOnly";



const font = Ubuntu({subsets:["latin"], weight:['400', "700"]})
export const metadata: Metadata = {
  title: "Our Budget App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const currentUser = await getCurrentUser()
    const years = await getAllYears()
    
  return (
    <html lang="en">
      <body
        className={font.className}
      >
        <ClientOnly>
          <RegisterModal />
          <LoginModal />
          <ToastLib />
          <Header currentUser = {currentUser} years={years}/>
          {children}
        </ClientOnly>
      </body>
    </html>
  );
}
